#!/usr/bin/env node
'use strict';

const path = require('path');
const gh = require('gh-got');
const Ora = require('ora');
const writeJsonFile = require('write-json-file');

const emojis = gh('emojis').then(res => {
  writeJsonFile(path.resolve(__dirname, '../data/emojis.json'), res.body, {
    indent: 2,
    sortKeys: true
  });
});

Ora.promise(emojis, {
  text: 'getting emojis 😄'
});
