#!/usr/bin/env node
'use strict';

const path = require('path');
const gh = require('gh-got');
const ora = require('ora');
const writeJsonFile = require('write-json-file');

const spinner = ora('getting emojis 😄').start();

gh('emojis').then(res => {
  const emojis = res.body;
  const file = path.resolve(__dirname, '../data/emojis.json');

  writeJsonFile(file, emojis, {
    indent: 2,
    sortKeys: true
  })
    .then(res => {
      spinner.succeed(`👍`);
    })
    .catch(err => {
      spinner.fail(err.message);
    });
});
