#!/usr/bin/env sh
#
# compile styles.

cd "$(dirname "$0")/.."

set -e

if [ ! -d node_modules ]; then
  script/bootstrap
fi

node_modules/.bin/node-sass --include-path scss --output-style compressed scss/style.scss assets/style.css
